site_name: Victor Code Notes
docs_dir: pages
site_dir: docs
pages:
- Home: index.md
- Code Notes:
    - Bash: bash.md
    - Docker: docker.md
    - Hive: hive.md
    - Java: java.md
    - Scala: 
       - 'Parse a JSON' : scala/json.md
    - Spring:
       - 'Core': spring/core.md
       - 'Batch': spring/batch.md
       - 'Integration': spring/integration.md
       - 'Security': spring/security.md       
    - Spark: spark.md

theme: readthedocs
