site_name: Victor Code Notes
docs_dir: pages
site_dir: docs
pages:
- Home: index.md
- Code Notes:
    - Bash: bash.md
    - Big Data:
      - 'Hive': bigdata/hive.md
      - 'Parquet' : bigdata/parquet.md
    - Docker:
       - 'Cloudera Quickstart' : docker/cloudera.md     
       - 'SQL Server' : docker/sqlserver.md
    - ElasticSearch:
       - 'Geographical' : elasticsearch/geohashing.md
    - Git:
       - 'SSH Usage' : git/ssh-clone.md
    - Java: 
       - 'Cryptography' : java/crypto.md
       - 'JVM' : java/jvm.md
       - 'File/URL/HDFS Properties' : java/properties.md
    - React:
       - 'Leaftlet sample': react/leaftletsample.html    
    - Scala: 
       - 'Cheatsheets' : scala/cheatsheets.md
       - 'Parallel Collections' : scala/parallel.md       
       - 'Parse a JSON' : scala/json.md
    - Spring:
       - 'Cloud' : spring/cloud.md
       - 'Core': spring/core.md
       - 'Batch': spring/batch.md
       - 'Integration': spring/integration.md
       - 'Security': spring/security.md       
       -  'Spring IO 2018': spring/spring_io_sessions.md
    - Spark: 
       - 'DataFrames' : spark/spark.md
       - 'Structured Streaming' : spark/structured_streaming.md

theme: readthedocs
