site_name: Victor Code Notes
docs_dir: pages
site_dir: docs
pages:
- Home: index.md
- Code Notes:
    - Bash: bash.md
    - Big Data:
      - 'Hive': bigdata/hive.md
      - 'Parquet' : bigdata/parquet.md
      - Spark: 
         - 'DataFrames' : spark/spark.md
         - 'Structured Streaming' : spark/structured_streaming.md      
    - Docker:
       - 'Cloudera Quickstart' : docker/cloudera.md     
       - 'Jupyter Notebooks' : docker/jupyter.md
       - 'Kubernetes' : docker/kind.md
       - 'SQL Server' : docker/sqlserver.md
    - ElasticSearch:
       - 'Geographical' : elasticsearch/geohashing.md
    - Git:
       - 'SSH Usage' : git/ssh-clone.md
    - Go:
       - 'Basic Docker image' : go/go_docker.md
    - Java: 
       - 'Cryptography' : java/crypto.md
       - 'JVM' : java/jvm.md
       - 'File/URL/HDFS Properties' : java/properties.md
    - Python:
        - 'OpenApi Python client' : python/python_clients.md
    - Scala: 
       - 'Cheatsheets' : scala/cheatsheets.md
       - 'Parallel Collections' : scala/parallel.md       
       - 'Parse a JSON' : scala/json.md
    - Spring:
       - 'Caching' : spring/caching.md
       - 'Cloud' : spring/cloud.md
       - 'Core':
            - 'Datasources' : spring/core.md
            - 'Profiles' : spring/core_profiles.md
            - 'SSL Support' : spring/core_ssl.md
       - 'Batch': spring/batch.md
       - 'Integration': spring/integration.md
       - 'Security':
           - 'Basic Setup' : spring/security_basic.md
           - 'Method Security' : spring/security_method.md
       -  'Spring IO 2018': spring/spring_io_sessions.md


theme: readthedocs
